#version: "3.7"
x-api: &default-api
  image: ghcr.io/openimis/openimis-be:${BE_TAG:-develop}
  environment:
    - DB_HOST=${DB_HOST}
    - DB_PORT=${DB_PORT}
    - DB_NAME=${DB_NAME}
    - DB_USER=${DB_USER}
    - DB_PASSWORD=${DB_PASSWORD}
    - SITE_ROOT=api
    - SITE_URL=${DOMAIN}
    - CELERY_BROKER_URL=amqp://rabbitmq
    - DB_ENGINE=${DB_ENGINE}
    - MODE=${MODE:-Prod}
  volumes:
    - photos:/openimis-be/openIMIS/images/insurees
    - ../openimis-be_py/openimis.json:/openimis-be/openimis.json
    - ../openimis-be_py/script/entrypoint.sh:/openimis-be/openimis-be/script/entrypoint.sh
    - ../openimis-be_py/script/reportbro.py:/openimis-be/script/reportbro.py
  depends_on:
    db:
      condition: service_healthy
  networks:
    openimis-net:
  restart: always

services:
  frontend:
    container_name: ${PROJECT_NAME:-openimis}-frontend
    build:
      context: ../openimis-fe_js/
      args:
        OPENIMIS_CONF_JSON: ${OPENIMIS_FE_CONF_JSON}
    image: openimis/frontend:${PROJECT_NAME:-local}
    restart: always
    environment:
      - REACT_APP_API_URL=api
      - NEW_OPENIMIS_HOST=${DOMAIN}
      - OPENIMIS_CONF_JSON=${OPENIMIS_FE_CONF_JSON}
      - OPENSEARCH_BASIC_TOKEN=${OPENSEARCH_BASIC_TOKEN}
    networks:
      openimis-net:
    ports:
      - ${HTTP_PORT:-80}:80
      - ${HTTPS_PORT:-443}:443
    depends_on:
      - backend
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
      # uncomment to use custom openimis.conf
      - ./conf/nginx:/conf/
  backend:
    <<: *default-api
    container_name: ${PROJECT_NAME:-openimis}-api
    command: start      
  
  worker:
    <<: *default-api
    container_name: ${PROJECT_NAME:-openimis}-worker
    command: worker
  rabbitmq:
    container_name: ${PROJECT_NAME:-openimis}-rabbitmq
    image: rabbitmq:3-management
    restart: always
    networks:
      openimis-net:
networks:
  openimis-net:
    name: "${PROJECT_NAME:-openimis}-net"
volumes:
  database:
  photos:
